import type { Metadata } from "next";
import React from "react";
import localFont from "next/font/local";
import { ConfigProvider } from "antd";
import "@ant-design/v5-patch-for-react-19"; // Import antv5 compatibility package for React 19
import "../../styles/globals.css";
import Navbar from "../../components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#0066cc",
            },
          }}
        >
          <React.Fragment>
            <Navbar />
            {children}
          </React.Fragment>
        </ConfigProvider>
      </body>
    </html>
  );
}
